### ISSUE TITLE
torch_cluster version incompatible 

### ISSUE THREAD

**Issue by XZhang-ML** [vsomnath/aligned_diffusion_bridges#2]
Hi thanks for the great work and sharing the codes!

I have tried to install the package using [build_env.sh](https://github.com/IBM/aligned_diffusion_bridges/blob/main/build_env.sh) on Debian x86_64 GNU/Linux, cuda 11.3 machine. But got torch_cluster incompatible with cuda issue, below is the error information:
```
    return torch.ops.torch_cluster.radius(x, y, ptr_x, ptr_y, r,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                          max_num_neighbors, num_workers)
RuntimeError: Not compiled with CUDA support
```
Here is my env: 

```
# Name                    Version                   Build  Channel
torch                     1.12.0+cu113             pypi_0    pypi
torch-cluster             1.6.1                    pypi_0    pypi
torch-ema                 0.3                      pypi_0    pypi
torch-geometric           2.3.1                    pypi_0    pypi
torch-scatter             2.1.1                    pypi_0    pypi
torch-sparse              0.6.17                   pypi_0    pypi
torchaudio                0.12.0+cu113             pypi_0    pypi
torchvision               0.13.0+cu113             pypi_0    pypi
```

I see you run the model on linux cuda11.3 machine as well, would you mind sharing your env information of torch-pkg here, please? 
Thanks

**Comment by vsomnath** [comment]
Hi, sorry for the delay in responding!

Let me retry creating the environment on the cluster and see if the instructions work as expected.

**Comment by vsomnath** [comment]
I cleared the environment installation, and removed any cache, and recreated the environment. This is how it looks for me:
![image](https://github.com/vsomnath/aligned_diffusion_bridges/assets/32259379/c592cba6-7553-4dbd-8bf3-a6d760590c78)

This environment was made on a cluster node that only has cpu, so maybe there is an installation different on a pure GPU node.

Let me know if clearing the cache and environment and rerunning `./build_env.sh` fixes your issue -- happy to take a closer look otherwise!

**Comment by vsomnath** [comment]
Closing this issue right now -- feel free to reopen if necessary!
