### ISSUE TITLE
Inference Step:  Use of Equation 5 over Equation 6

### ISSUE THREAD

**Issue by HanLiii** [vsomnath/aligned_diffusion_bridges#3]
Hi Vignesh,

Thank you for your excellent work. I have a question regarding the inference step: why should we use Equation 5 instead of Equation 6? It seems that Equation 5 is more concise. Could you clarify this choice?

**Comment by vsomnath** [comment]
Hi, sorry for the very delayed response here. Are you referring to the latest version on arxiv (https://arxiv.org/abs/2302.11419) for Eq. 5 and Eq. 6?

We use Eq. 5 instead of Eq. 6 because the drift in Eq. 5 is not dependent on `x_1` (which we are trying to predict), while Eq 6 has the h-transform term dependent on `x_1`.
